version: "3.7"
services:
  mongodb:
    image: "mongo:4.4.3"
    container_name: mongo
    restart: always
    ports:
      - 27018:27017
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: order_service